// SprTool.cs – Kingsoft Sword3 SPR sprite tool
// Target: .NET Framework 4.x  (C# 5/6 compatible)
//
// Usage:
//   SprTool unpack <file.spr> <output_dir>
//   SprTool pack   <input_dir> <output.spr> [--no-transp]
//                  [--centerx N] [--centery N] [--directions N] [--interval N]
//
// SPR layout:
//   SPRHEAD 32 bytes: "SPR\0" + W,H,CX,CY,Frames,Colors,Dirs,Interval,Reserved[6] (ushort LE)
//   KPAL24[Colors]   {R,G,B} 3 bytes each
//   SPROFFS[Frames]  {Offset(uint), Length(uint)} relative to sprite block
//   SPRFRAME:        Width(2) Height(2) OffsetX(2) OffsetY(2) + RLE bytes
//
// RLE:
//   BYTE count
//   BYTE alpha  — 0=transparent run (skip count pixels, no data)
//                 1-255=opaque run (alpha is the per-run blend factor;
//                        count palette-index bytes follow)
//
// Frames are saved as 32-bit RGBA PNG:
//   transparent pixel → A=0
//   opaque pixel      → A = original RLE alpha (1-255), RGB = palette colour
//
// palette.bin (raw Colors×3 RGB bytes) is saved alongside so pack can map
// colours back to exact palette indices without guessing.
//
// frame_info.txt stores Frame{N}=ox,oy,fw,fh so pack can reproduce the exact
// declared frame rectangle (which may be larger than the tight bounding box).

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;

class SprTool
{
    static int Main(string[] args)
    {
        if (args.Length < 1) { PrintUsage(); return 1; }
        try
        {
            string cmd = args[0].ToLower();
            if (cmd == "unpack" && args.Length >= 3) return Unpack(args[1], args[2]);
            if (cmd == "pack"   && args.Length >= 3) return Pack(args[1], args[2], args.Skip(3).ToArray());
            PrintUsage(); return 1;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine("Error: " + ex.Message);
            Console.Error.WriteLine(ex.StackTrace);
            return 1;
        }
    }

    static void PrintUsage()
    {
        Console.WriteLine("SprTool – Kingsoft Sword3 SPR utility (.NET FX 4.x)");
        Console.WriteLine("  SprTool unpack <file.spr> <output_dir>");
        Console.WriteLine("  SprTool pack   <input_dir> <output.spr> [--no-transp]");
        Console.WriteLine("                 [--centerx N] [--centery N]");
        Console.WriteLine("                 [--directions N] [--interval N]");
        Console.WriteLine("  Frames are stored as 32-bit RGBA PNG (A=0 transparent, A=alpha otherwise).");
    }

    // ================================================================ UNPACK
    static int Unpack(string sprPath, string outDir)
    {
        if (!File.Exists(sprPath)) throw new FileNotFoundException("SPR not found: " + sprPath);
        byte[] data = File.ReadAllBytes(sprPath);
        if (data.Length < 32) throw new InvalidDataException("File too small.");
        if (data[0]!='S'||data[1]!='P'||data[2]!='R') throw new InvalidDataException("Bad magic.");

        int p = 4;
        ushort width      = LE16(data, p); p += 2;
        ushort height     = LE16(data, p); p += 2;
        ushort centerX    = LE16(data, p); p += 2;
        ushort centerY    = LE16(data, p); p += 2;
        ushort frames     = LE16(data, p); p += 2;
        ushort colors     = LE16(data, p); p += 2;
        ushort directions = LE16(data, p); p += 2;
        ushort interval   = LE16(data, p); p += 2;
        p += 12;

        Console.WriteLine(string.Format(
            "SPR: {0}x{1}  frames={2}  colors={3}  center=({4},{5})  dir={6}  interval={7}",
            width, height, frames, colors, centerX, centerY, directions, interval));

        byte[] palR = new byte[colors], palG = new byte[colors], palB = new byte[colors];
        for (int i = 0; i < colors; i++) { palR[i]=data[p]; palG[i]=data[p+1]; palB[i]=data[p+2]; p+=3; }

        uint[] offOff = new uint[frames], offLen = new uint[frames];
        for (int i = 0; i < frames; i++) { offOff[i]=LE32(data,p); p+=4; offLen[i]=LE32(data,p); p+=4; }
        int sprBase = p;

        Directory.CreateDirectory(outDir);

        // Save palette.bin
        byte[] palBin = new byte[colors * 3];
        for (int i = 0; i < colors; i++) { palBin[i*3]=palR[i]; palBin[i*3+1]=palG[i]; palBin[i*3+2]=palB[i]; }
        File.WriteAllBytes(Path.Combine(outDir, "palette.bin"), palBin);

        var info = new List<string>();
        info.Add("# SPR frame info – generated by SprTool");
        info.Add("Width="      + width);
        info.Add("Height="     + height);
        info.Add("CenterX="    + centerX);
        info.Add("CenterY="    + centerY);
        info.Add("Directions=" + directions);
        info.Add("Interval="   + interval);
        info.Add("Colors="     + colors);
        info.Add("Frames="     + frames);

        for (int f = 0; f < frames; f++)
        {
            int fp = sprBase + (int)offOff[f];
            ushort fw = LE16(data,fp); fp+=2;
            ushort fh = LE16(data,fp); fp+=2;
            ushort ox = LE16(data,fp); fp+=2;
            ushort oy = LE16(data,fp); fp+=2;

            byte[] indices; byte[] alphaMap;
            DecodeRLE(data, fp, fw, fh, out indices, out alphaMap);

            string png = Path.Combine(outDir, string.Format("frame_{0:D4}.png", f));
            SaveRgbaPng(png, fw, fh, indices, alphaMap, palR, palG, palB, colors);

            // Store ox,oy,fw,fh for exact round-trip
            info.Add(string.Format("Frame{0}={1},{2},{3},{4}", f, ox, oy, fw, fh));
            Console.WriteLine(string.Format("  frame {0:D4}: {1}x{2}  offset=({3},{4})  -> {5}",
                f, fw, fh, ox, oy, Path.GetFileName(png)));
        }

        File.WriteAllLines(Path.Combine(outDir, "frame_info.txt"), info.ToArray());
        Console.WriteLine("Done. " + frames + " frame(s) written to " + outDir);
        return 0;
    }

    // ================================================================== PACK
    static int Pack(string inputDir, string outSpr, string[] extraArgs)
    {
        bool useTransp = true;
        ushort centerX=0, centerY=0, directions=1, interval=1;
        for (int i = 0; i < extraArgs.Length; i++)
            switch (extraArgs[i].ToLower())
            {
                case "--no-transp":  useTransp  = false;                         break;
                case "--centerx":    centerX    = ushort.Parse(extraArgs[++i]);  break;
                case "--centery":    centerY    = ushort.Parse(extraArgs[++i]);  break;
                case "--directions": directions = ushort.Parse(extraArgs[++i]);  break;
                case "--interval":   interval   = ushort.Parse(extraArgs[++i]);  break;
            }

        // Read frame_info.txt
        // FIX #1: "Frames" starts with "Frame" — skip it explicitly.
        // FIX #4: Frame line stores ox,oy,fw,fh for exact frame rectangle.
        var frameInfo = new Dictionary<int, ushort[]>(); // [ox,oy,fw,fh]
        ushort sprWidth=0, sprHeight=0;
        string infoPath = Path.Combine(inputDir, "frame_info.txt");
        if (File.Exists(infoPath))
            foreach (string line in File.ReadAllLines(infoPath))
            {
                if (line.StartsWith("#") || !line.Contains("=")) continue;
                string[] kv  = line.Split(new char[]{'='}, 2);
                string   key = kv[0].Trim(), val = kv[1].Trim();
                if      (key == "Width")      sprWidth    = ushort.Parse(val);
                else if (key == "Height")     sprHeight   = ushort.Parse(val);
                else if (key == "CenterX")    centerX     = ushort.Parse(val);
                else if (key == "CenterY")    centerY     = ushort.Parse(val);
                else if (key == "Directions") directions  = ushort.Parse(val);
                else if (key == "Interval")   interval    = ushort.Parse(val);
                else if (key.StartsWith("Frame") && key != "Frames")
                {
                    int fi = int.Parse(key.Substring(5));
                    string[] parts = val.Split(',');
                    frameInfo[fi] = new ushort[]{
                        ushort.Parse(parts[0]), ushort.Parse(parts[1]),
                        parts.Length>=4 ? ushort.Parse(parts[2]) : (ushort)0,
                        parts.Length>=4 ? ushort.Parse(parts[3]) : (ushort)0
                    };
                }
            }

        // Collect images (PNG preferred, BMP legacy)
        string[] imgs = Directory.GetFiles(inputDir, "frame_????.png").OrderBy(x=>x).ToArray();
        bool isPng = true;
        if (imgs.Length == 0) { imgs = Directory.GetFiles(inputDir, "frame_????.bmp").OrderBy(x=>x).ToArray(); isPng = false; }
        if (imgs.Length == 0) throw new FileNotFoundException("No frame_NNNN.png/.bmp in: " + inputDir);
        Console.WriteLine("Packing " + imgs.Length + " frame(s) from " + inputDir);

        // Palette
        byte[] palR, palG, palB; ushort colors;
        string palPath = Path.Combine(inputDir, "palette.bin");
        if (File.Exists(palPath))
        {
            byte[] pd = File.ReadAllBytes(palPath);
            colors = (ushort)(pd.Length / 3);
            palR = new byte[colors]; palG = new byte[colors]; palB = new byte[colors];
            for (int i=0;i<colors;i++){palR[i]=pd[i*3];palG[i]=pd[i*3+1];palB[i]=pd[i*3+2];}
        }
        else if (!isPng)
        {
            using (Bitmap b0 = new Bitmap(imgs[0]))
            {
                if (b0.PixelFormat != PixelFormat.Format8bppIndexed)
                    throw new InvalidDataException(Path.GetFileName(imgs[0]) + " is not 8bpp indexed.");
                Color[] ent = b0.Palette.Entries;
                colors=(ushort)ent.Length;
                palR=new byte[colors];palG=new byte[colors];palB=new byte[colors];
                for(int i=0;i<colors;i++){palR[i]=ent[i].R;palG[i]=ent[i].G;palB[i]=ent[i].B;}
            }
        }
        else throw new InvalidDataException("palette.bin not found. Re-run unpack first.");

        var rleList = new List<byte[]>();
        var hdrList = new List<ushort[]>();

        for (int fi = 0; fi < imgs.Length; fi++)
        {
            int bw, bh;
            byte[] palIdx; byte[] alphaMap; // alphaMap: 0=transparent, 1-255=opaque blend

            if (isPng)
                LoadRgbaPng(imgs[fi], palR, palG, palB, colors, out bw, out bh, out palIdx, out alphaMap);
            else
            {
                using (Bitmap bmp = new Bitmap(imgs[fi]))
                {
                    if (bmp.PixelFormat != PixelFormat.Format8bppIndexed)
                        throw new InvalidDataException(Path.GetFileName(imgs[fi]) + " not 8bpp indexed.");
                    bw=bmp.Width; bh=bmp.Height;
                    BitmapData bd = bmp.LockBits(new Rectangle(0,0,bw,bh),
                        ImageLockMode.ReadOnly, PixelFormat.Format8bppIndexed);
                    byte[] pix = new byte[bh*bd.Stride];
                    Marshal.Copy(bd.Scan0, pix, 0, pix.Length); bmp.UnlockBits(bd);
                    int st = bd.Stride;
                    byte ck = useTransp ? pix[0] : (byte)0xFF;
                    palIdx   = new byte[bw*bh];
                    alphaMap = new byte[bw*bh];
                    for (int y=0;y<bh;y++) for (int x=0;x<bw;x++)
                    {
                        byte v = pix[y*st+x];
                        palIdx[y*bw+x]   = v;
                        alphaMap[y*bw+x] = (useTransp && v==ck) ? (byte)0 : (byte)255;
                    }
                }
            }

            // Determine frame rectangle
            ushort ox, oy, rectW, rectH;
            if (frameInfo.ContainsKey(fi) && frameInfo[fi][2] > 0 && frameInfo[fi][3] > 0)
            {
                ox=frameInfo[fi][0]; oy=frameInfo[fi][1];
                rectW=frameInfo[fi][2]; rectH=frameInfo[fi][3];
            }
            else
            {
                int left=bw, right=0, top=bh, bottom=0;
                if (!useTransp) { left=0; right=bw; top=0; bottom=bh; }
                else
                {
                    for (int x=0;x<bw&&left==bw;x++)
                        for (int y=0;y<bh;y++) if (alphaMap[y*bw+x]!=0){left=x;break;}
                    for (int x=bw-1;x>=0&&right==0;x--)
                        for (int y=0;y<bh;y++) if (alphaMap[y*bw+x]!=0){right=x+1;break;}
                    for (int y=0;y<bh&&top==bh;y++)
                        for (int x=0;x<bw;x++) if (alphaMap[y*bw+x]!=0){top=y;break;}
                    for (int y=bh-1;y>=0&&bottom==0;y--)
                        for (int x=0;x<bw;x++) if (alphaMap[y*bw+x]!=0){bottom=y+1;break;}
                    if (left>=right||top>=bottom){left=0;right=0;top=0;bottom=0;}
                }
                ox = frameInfo.ContainsKey(fi) ? frameInfo[fi][0] : (ushort)left;
                oy = frameInfo.ContainsKey(fi) ? frameInfo[fi][1] : (ushort)top;
                rectW=(ushort)(right-left); rectH=(ushort)(bottom-top);
            }

            // RLE encode
            // FIX #3: write actual alpha value per run (not always 255).
            // FIX #3: group consecutive pixels with same non-zero alpha into one run.
            var ms  = new MemoryStream(rectW * rectH + rectH * 4);
            var bwr = new BinaryWriter(ms);

            for (int row = 0; row < rectH; row++)
            {
                int nx = 0, nLeft = rectW;
                while (nLeft > 0)
                {
                    // Transparent run: consecutive pixels with alphaMap==0
                    int tc = 0;
                    if (useTransp)
                    {
                        int tx = nx;
                        while (nLeft-tc > 0 && tc < 255)
                        {
                            byte a = (row < bh && tx < bw) ? alphaMap[row*bw+tx] : (byte)0;
                            if (a != 0) break;
                            tc++; tx++;
                        }
                    }
                    if (tc > 0)
                    {
                        bwr.Write((byte)tc); bwr.Write((byte)0);
                        nx += tc; nLeft -= tc; continue;
                    }

                    // Opaque run: consecutive pixels with same non-zero alpha
                    byte runAlpha = (row < bh && nx < bw) ? alphaMap[row*bw+nx] : (byte)0;
                    if (runAlpha == 0) { nx++; nLeft--; continue; } // safety
                    int dc = 0;
                    { int dx = nx;
                      while (nLeft-dc > 0 && dc < 255)
                      {
                          byte a = (row < bh && dx < bw) ? alphaMap[row*bw+dx] : (byte)0;
                          if (a == 0 || a != runAlpha) break;
                          dc++; dx++;
                      }
                    }
                    if (dc > 0)
                    {
                        bwr.Write((byte)dc); bwr.Write(runAlpha);
                        for (int k=0;k<dc;k++)
                            bwr.Write((row<bh&&(nx+k)<bw) ? palIdx[row*bw+(nx+k)] : (byte)0);
                        nx += dc; nLeft -= dc;
                    }
                    else { nx++; nLeft--; } // safety
                }
            }
            bwr.Flush();
            byte[] rleData = ms.ToArray();
            bwr.Close();

            rleList.Add(rleData);
            hdrList.Add(new ushort[]{ rectW, rectH, ox, oy });
            if (bw > sprWidth)  sprWidth  = (ushort)bw;
            if (bh > sprHeight) sprHeight = (ushort)bh;
            Console.WriteLine(string.Format("  frame {0:D4}: {1}x{2}  offset=({3},{4})  rle={5} bytes",
                fi, rectW, rectH, ox, oy, rleData.Length));
        }

        // Build SPRFRAME blobs
        var blobs = new List<byte[]>();
        for (int fi = 0; fi < rleList.Count; fi++)
        {
            var ms2 = new MemoryStream(8 + rleList[fi].Length);
            var bw2 = new BinaryWriter(ms2);
            bw2.Write(hdrList[fi][0]); bw2.Write(hdrList[fi][1]);
            bw2.Write(hdrList[fi][2]); bw2.Write(hdrList[fi][3]);
            bw2.Write(rleList[fi]); bw2.Flush();
            blobs.Add(ms2.ToArray()); bw2.Close();
        }

        // Write SPR
        using (var fs = new FileStream(outSpr, FileMode.Create, FileAccess.Write))
        using (var fw = new BinaryWriter(fs))
        {
            fw.Write((byte)'S'); fw.Write((byte)'P'); fw.Write((byte)'R'); fw.Write((byte)0);
            fw.Write(sprWidth); fw.Write(sprHeight);
            fw.Write(centerX);  fw.Write(centerY);
            fw.Write((ushort)blobs.Count); fw.Write(colors);
            fw.Write(directions); fw.Write(interval);
            for (int r=0;r<6;r++) fw.Write((ushort)0);
            for (int i=0;i<colors;i++){fw.Write(palR[i]);fw.Write(palG[i]);fw.Write(palB[i]);}
            uint run=0;
            for (int fi=0;fi<blobs.Count;fi++){fw.Write(run);fw.Write((uint)blobs[fi].Length);run+=(uint)blobs[fi].Length;}
            for (int fi=0;fi<blobs.Count;fi++) fw.Write(blobs[fi]);
            fw.Flush();
            Console.WriteLine("Done. "+blobs.Count+" frame(s) -> "+outSpr+"  ("+fs.Length+" bytes)");
        }
        return 0;
    }

    // ============================================================ RLE decode
    // alphaMap: 0=transparent, 1-255=the actual per-run blend alpha
    static void DecodeRLE(byte[] data, int pos, int width, int height,
                          out byte[] indices, out byte[] alphaMap)
    {
        indices  = new byte[width * height];
        alphaMap = new byte[width * height]; // 0 = transparent
        for (int row = 0; row < height; row++)
        {
            int col = 0;
            while (col < width)
            {
                if (pos >= data.Length) break;
                int  count = data[pos++];
                byte alpha = pos < data.Length ? data[pos++] : (byte)0;
                if (alpha == 0)
                {
                    col += count;
                }
                else
                {
                    for (int i = 0; i < count && col < width; i++, col++)
                        if (pos < data.Length)
                        {
                            indices [row*width+col] = data[pos++];
                            alphaMap[row*width+col] = alpha; // preserve exact blend value
                        }
                }
            }
        }
    }

    // ======================================================= save 32bpp RGBA PNG
    // Alpha channel stores the RLE blend value (0=transparent, 1-255=opaque blend)
    static void SaveRgbaPng(string path, int width, int height,
        byte[] indices, byte[] alphaMap,
        byte[] palR, byte[] palG, byte[] palB, int colors)
    {
        using (Bitmap bmp = new Bitmap(width, height, PixelFormat.Format32bppArgb))
        {
            for (int y = 0; y < height; y++)
                for (int x = 0; x < width; x++)
                {
                    int  idx = indices [y*width+x];
                    byte a   = alphaMap[y*width+x];
                    byte r   = (idx<colors) ? palR[idx] : (byte)0;
                    byte g   = (idx<colors) ? palG[idx] : (byte)0;
                    byte b   = (idx<colors) ? palB[idx] : (byte)0;
                    bmp.SetPixel(x, y, Color.FromArgb(a, r, g, b));
                }
            bmp.Save(path, ImageFormat.Png);
        }
    }

    // ======================================================= load RGBA PNG
    // Returns alphaMap: 0=transparent, else the PNG alpha (= original RLE blend)
    static void LoadRgbaPng(string path,
        byte[] palR, byte[] palG, byte[] palB, int colors,
        out int bw, out int bh, out byte[] palIdx, out byte[] alphaMap)
    {
        using (Bitmap bmp = new Bitmap(path))
        {
            bw=bmp.Width; bh=bmp.Height;
            palIdx   = new byte[bw*bh];
            alphaMap = new byte[bw*bh];

            Bitmap src = bmp;
            bool conv = (bmp.PixelFormat != PixelFormat.Format32bppArgb);
            if (conv) src = bmp.Clone(new Rectangle(0,0,bw,bh), PixelFormat.Format32bppArgb);

            BitmapData bd = src.LockBits(new Rectangle(0,0,bw,bh),
                ImageLockMode.ReadOnly, PixelFormat.Format32bppArgb);
            byte[] raw = new byte[bh*bd.Stride];
            Marshal.Copy(bd.Scan0, raw, 0, raw.Length);
            src.UnlockBits(bd);
            if (conv) src.Dispose();

            for (int y=0;y<bh;y++) for (int x=0;x<bw;x++)
            {
                int  off = y*bd.Stride + x*4;
                byte pb=raw[off], pg=raw[off+1], pr=raw[off+2], pa=raw[off+3];
                alphaMap[y*bw+x] = pa; // 0=transparent, else blend alpha
                if (pa != 0)
                    palIdx[y*bw+x] = FindNearest(pr, pg, pb, palR, palG, palB, colors);
            }
        }
    }

    static byte FindNearest(byte r, byte g, byte b,
        byte[] palR, byte[] palG, byte[] palB, int colors)
    {
        int best=0; long best2=long.MaxValue;
        for (int i=0;i<colors;i++)
        {
            long dr=r-palR[i], dg=g-palG[i], db=b-palB[i];
            long d=dr*dr+dg*dg+db*db;
            if (d<best2){best2=d;best=i;}
            if (d==0) break;
        }
        return (byte)best;
    }

    static ushort LE16(byte[] d, int p) { return (ushort)(d[p]|(d[p+1]<<8)); }
    static uint   LE32(byte[] d, int p) { return (uint)(d[p]|(d[p+1]<<8)|(d[p+2]<<16)|(d[p+3]<<24)); }
}
